### ISSUE TITLE
Feedback: Botkit channel

### ISSUE THREAD

**Issue by ken9ross** [leomchan/botkit-zulip#1]
BotKit has a slack workspace at dev4slack.slack.com

I posted a question about  using botkit over Zulip and mentioned this npm package and they didn't know about it. It might be worth approaching them and getting a dedicated channel over there or at least making sure the botkit folks know about this package

**Comment by leomchan** [comment]
Hi ken,

Thanks for the heads up. I'll look into it.

Thanks,

Leo
